# Generated by Django 2.0.5 on 2018-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180605_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_mobile',
            field=models.IntegerField(default=None),
        ),
    ]
